### ISSUE TITLE
Invalid link

### ISSUE THREAD

**Issue by suBDavis** [cconsidine/awesome-hackathons#4]
https://github.com/cconsidine/awesome-hackathons/blame/master/README.md#L34

Not a valid project link

**Comment by kedarv** [comment]
Please see #3

**Comment by suBDavis** [comment]
Ah good, just wanted to let you know.  

As a point of style, I think the issue tracker should be used to track issues.  If an issue comes up like this, the issue tracker exists to prove that there was a problem, document updates, and then gets closed when the issue is resolved, not as a way of indicating that you acknowledge the problem.

A broken link is sort of like known bug, and you don't close mark those as resolved just because you can't do anything about them right now.  Otherwise people who find the bug just keep reporting it as an unresolved issue.

Just my 2 cents!  Cheers.
